# Generated by Django 3.1.1 on 2021-10-24 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheeses', '0002_auto_20211009_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheese',
            name='firmness',
            field=models.CharField(choices=[('unspecified', 'Unspecified'), ('soft', 'Soft'), ('semi-soft', 'Semi-Soft'), ('semi-hard', 'Semi-Hard'), ('hard', 'Hard'), ('fresh soft', 'Fresh Soft'), ('firm', 'Firm'), ('artisan', 'Artisan'), ('semi-firm', 'Semi-Firm'), ('fresh firm', 'Fresh Firm')], default='unspecified', max_length=20, verbose_name='Firmness'),
        ),
    ]
